### ISSUE TITLE
.toml config file not found

### ISSUE THREAD

**Issue by yangzheng-121** [vocalpy/vak#506]
I was going through the tutorial in the vak website(https://vak.readthedocs.io/en/latest/get_started/autoannotate.html#autoannotate)
I met this error when preparing the dataset, and I've downloaded all the files needed.

(tweetynet) C:\Users\LabUser>vak prep gy6or6_train.toml
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tweetynet\Scripts\vak-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\envs\tweetynet\lib\site-packages\vak\__main__.py", line 45, in main
    cli.cli(command=args.command, config_file=args.configfile)
  File "C:\ProgramData\Anaconda3\envs\tweetynet\lib\site-packages\vak\cli\cli.py", line 30, in cli
    COMMAND_FUNCTION_MAP[command](toml_path=config_file)
  File "C:\ProgramData\Anaconda3\envs\tweetynet\lib\site-packages\vak\cli\prep.py", line 84, in prep
    config_toml = _load_toml_from_path(toml_path)
  File "C:\ProgramData\Anaconda3\envs\tweetynet\lib\site-packages\vak\config\parse.py", line 165, in _load_toml_from_path
    raise FileNotFoundError(f".toml config file not found: {toml_path}")
FileNotFoundError: .toml config file not found: gy6or6_train.toml

**Comment by NickleDave** [comment]
Hi @yangzheng-121 sorry you're running into this issue and thank you for letting us know

When you say you downloaded all the files needed, does that include the  gy6or6_train.toml config file?

I mean the ones that are linked to in step 4 here:
https://vak.readthedocs.io/en/latest/get_started/autoannotate.html#set-up

This is the direct link for the one you need right now:
https://vak.readthedocs.io/en/latest/_downloads/817549abdfad84278f9184d30b61c03d/gy6or6_train.toml

If you have downloaded it already, are you in the same directory as the config file when you run the command that gives you the error?
I.e., if you run
```console
(tweetynet) C:\Users\LabUser> dir
```
do you see some list of files that includes
```
gy6or6_train.toml
```
?

If not, that would explain why you're getting the `FileNotFound` error.

The `vak` command-line interface expects the second argument to be the path to the configuration file. So, when you type `vak prep gy6or6_train.toml` it's the same as writing `vak prep .\gy6or6_train.toml`, or, if you are in the `C:\Users\LabUser` directory, it's the same as writing `vak prep C:\Users\LabUser\gy6or6_train.toml`.

If that file is not in your current working directory, you can fix the error by either moving or copying the file to that directory, and continuing to type the relative path, or you can type the absolute path to the configuration file, e.g., if the file was in `C:\Users\LabUser\Downloads` but you were in `C:\Users\LabUser` then you can write:  
```console
(tweetynet) C:\Users\LabUser> vak prep C:\Users\LabUser\Downloads\gy6or6_train.toml
```

Let me know if that helps

**Comment by yangzheng-121** [comment]
Hi @NickleDave Thank you very much for answering my question!
I've changed the directory and it worked!

**Comment by NickleDave** [comment]
Great, glad to hear it @yangzheng-121 

I will close this issue for now but just let us know if you need any more help
