### ISSUE TITLE
DOC: vak prep input file formats documentation

### ISSUE THREAD

**Issue by ymk12345** [vocalpy/vak#516]
Hi, 

The documentation for the input files for the vak prep command show that the annotation filename and audio filename should carry the same filename with the only difference being the extension (ie, '.csv', '.wav'). However, this produces an error. The correct format for the annotation filename is the entire audio filename, including its '.wav' extension. If the audio file was 'filename.wav', the annotation filename should be 'filename.wav.csv' and not 'filename.csv'. Could we make this clear in the documentation?

Thanks!

**Comment by NickleDave** [comment]
Thank you @ymk12345 for catching this mistake in the docs

This section in `howto/howto_user_annot.md` needs to be fixed, specifically the mis-leading example that doesn't show the audio extension in front of the .csv extension:
https://github.com/vocalpy/vak/blob/main/doc/howto/howto_user_annot.md#explanation-of-when-you-can-use-the-simple-seq-format
