### ISSUE TITLE
DOC: Add suggestion to tutorial to use tar on windows, not WinZip

### ISSUE THREAD

**Issue by lmpascual** [vocalpy/vak#560]

**Comment by NickleDave** [comment]
Thank you @lmpascual for raising this issue, it will be helpful to 

Can you provide a couple more details for me? I should've asked before.
- What was the specific program you were using to unzip on Windows?
- Can you copy and paste the exact error that you got?

:pray: thank you! I will add you as a contributor and send you some VocalPy stickers I forgot to give you :smile_cat:

**Comment by NickleDave** [comment]
@lmpascual confirmed for me that she was using [WinZip](https://www.winzip.com/en/pages/download/winzip-b3/?x-target=ppc&promo=ppc)

**Comment by NickleDave** [comment]
Fixing this now and realized that I literally wrote you should use WinZip in the tutorial. Hmm, maybe I should've tested that.

Sorry @lmpascual -- my bad :flushed: :grimacing:   
Thanks again for catching it

**Comment by lmpascual** [comment]
No worries! What you showed me as a work is outlined here:  https://pureinfotech.com/extract-tar-gz-files-windows-10/
I was able to do it again myself following these instructions.
