### ISSUE TITLE
Error for duplicate value val_dur in gy6ro6_train.toml from tutorial

### ISSUE THREAD

**Issue by danielmk** [vocalpy/vak#731]
I was just trying to go through the tutorial (https://vak.readthedocs.io/en/latest/get_started/autoannotate.html#prepare-training-dataset) and I encountered a problem with the gy6or6_train.toml 

I got an error for duplicate values because val_dur appears twice in [PREP], I assume the second occurrence should be test_dur = 30?

This is the .toml file I downloaded: https://vak.readthedocs.io/en/latest/_downloads/817549abdfad84278f9184d30b61c03d/gy6or6_train.toml

**Comment by NickleDave** [comment]
Fixed in [f16acce](https://github.com/vocalpy/vak/commit/f15acce85f7d120d5c7f0258fad5f55e2b9d9e78), thanks again @danielmk for catching this

**Comment by NickleDave** [comment]
@all-contributors please add @danielmk for doc
